### ISSUE TITLE
Import error is occurred...

### ISSUE THREAD

**Issue by muks-mecha** [ccj5351/MS-Nets#1]
Hi 
I appreciate your great jobs.
But I met "Import error" when I started "do_main_msmnet.sh 0"

The following is the full text of the error.

Traceback (most recent call last):
  File "/home/ivcl/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ivcl/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ivcl/MS-Nets-master/main_msnet.py", line 38, in <module>
    from src.dataloader.data import get_training_set, get_iter_training_set, get_iter_testing_set
  File "/home/ivcl/MS-Nets-master/src/dataloader/data.py", line 6, in <module>
    from .dataset import IterableDatasetFromList, DatasetFromList
  File "/home/ivcl/MS-Nets-master/src/dataloader/dataset.py", line 21, in <module>
    from .cbmv_generator import (
  File "/home/ivcl/MS-Nets-master/src/dataloader/cbmv_generator.py", line 16, in <module>
    import src.cpp.lib.libmatchers as mtc
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1: undefined symbol: PyClass_Type
TASK_TYPE=val-30, flag=false

I think this error occurred because PyClass_Type defined in Python2 is not available in Python3, is that right?
If it's right, what should I do?

**Comment by muks-mecha** [comment]
Oh, sorry. 
Maybe path was mixed up during the installation process. 
When the virtual environment was initialized and proceeded again, it was moved on.

**Comment by ccj5351** [comment]
Thanks for your interest.
